### ISSUE TITLE
Limit view range to only directly visible items (FOV)

### ISSUE THREAD

**Issue by slemonide** [kuroneko1996/cyberlab#12]
Make it so that the player can only see items that are directly visible to her.

**Comment by kuroneko1996** [comment]
It requires FOV function, FOV should be recalculated only on the player movement. Python is slow.

**Comment by slemonide** [comment]
Here is an example of how it might look like:
<img width="481" alt="shadow_test" src="https://user-images.githubusercontent.com/7444258/29345326-e96fb9bc-81f2-11e7-8bf4-e540c7bff636.PNG">

**Comment by kuroneko1996** [comment]
~~**TODO**: Debug FOV~~
