### ISSUE TITLE
Add text field for storytelling

### ISSUE THREAD

**Issue by slemonide** [kuroneko1996/cyberlab#2]
- [x] Text field API
- [x] Events that will put text into the text field
- [x] Combine text messages into a queue
- [ ] Text typing effect

Add a text field where items and characters can write text.
It should look like this (doesn't have to be that fancy):
![JRPG with text field](https://c5.staticflickr.com/6/5506/30297497060_aa71598541_o.jpg)

Text could also be written when player passes certain location for the first time.

**Comment by slemonide** [comment]
We can also use zone editor from Tiled to denote zones upon entering which text would appear.

EDIT: done in 8c7829887c7d28302a2d856df31c16e208520dce

**Comment by kuroneko1996** [comment]
I suggest adding a text typing effect.

**Comment by slemonide** [comment]
Sounds good. We can also add an optional parameter for text zone triggers to invoke special effects.

**Comment by slemonide** [comment]
Done probably.
