### ISSUE TITLE
Messages: add support for cyrillic script

### ISSUE THREAD

**Issue by slemonide** [kuroneko1996/cyberlab#33]

**Comment by kuroneko1996** [comment]
~~There are two problems now.~~
Current custom font does not have cyrillic symbols.
~~Strings loaded from the json map have a different format/encoding(?)~~
~~However, changing the pygame font and pasting text into the source file like *u'Текст'* works.~~

**Comment by slemonide** [comment]
I have tested writing in cyrillic in the text events and it worked. So the main problem is with the fonts.

**Comment by slemonide** [comment]
Готово.
